### ISSUE TITLE
ERROR SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by danilo-dsf** [wliegel/youtube_webrtc_tutorial#1]
Hi! Thank you for the YouTube tutorial!

I tried to run this project and I got this message when I tried to call the other party: "ERROR SyntaxError: Unexpected token o in JSON at position 1".

![2021-09-22 15-45-26](https://user-images.githubusercontent.com/61921000/134404651-d70e2bec-527e-4fcd-812c-441a08238e95.gif)

Can anyone help me with that?

Thanks in advance.

P.S.: Sorry about my English, I'm still learning.

**Comment by danilo-dsf** [comment]
I had no answer, but it's ok. I found another way

**Comment by cartantino** [comment]
Hi! @danilo-dsf how did you solved your issue?

**Comment by danilo-dsf** [comment]
Hi, @cartantino, I used a tutorial about the peerjs lib.
Here is the link: [How To Build a Video Chat App from Scratch: WebRTC Demystified | Step by Step Tutorial p. 2 | Angular + PeerJS](https://levelup.gitconnected.com/how-to-build-a-video-chat-app-from-scratch-webrtc-demystified-step-by-step-tutorial-p-2e74767c673)

**Comment by aziz-del** [comment]
hello , i have exactly the same problem 
can anyone give me the exact solution please 
thanks a lot !!!

**Comment by danilo-dsf** [comment]
Sorry @aziz-del 
I still don't have an answer ;-;
